version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"

apache_fallback_resource: "/index.php"

command:
  build:
    - "composer update"

  test:
    - "vendor/bin/phpunit --verbose --testdox tests/"
